#ifndef CONFIG_H
#define CONFIG_H
#cmakedefine VERSION "@VERSION@"
#cmakedefine VERSION_PATCH "@VERSION_PATCH@"
#cmakedefine QTVERSION "@QTVERSION@"
#cmakedefine CMAKE_SOURCE_DIR "@CMAKE_SOURCE_DIR@"
#cmakedefine SEVENZIP_UNPACK_SUPPORT 1
#cmakedefine BZIP2_UNPACK_SUPPORT 1
#cmakedefine BUILD_TRANSLATIONS "@BUILD_TRANSLATIONS@"
#cmakedefine BUILD_WITH_SHA1_CHECKSUM 1
#cmakedefine INSTALLER_URL_PATH "@INSTALLER_URL_PATH@"
#cmakedefine INSTALLER_UPDATE_URL "@INSTALLER_UPDATE_URL@"
#cmakedefine INSTALLER_MIRROR_URL "@INSTALLER_MIRROR_URL@"
#cmakedefine INSTALLER_MIRROR_FALLBACK_URL "@INSTALLER_MIRROR_FALLBACK_URL@"
#include "debug.h"

#endif
